이번에는 머신러닝의 성능을 좌우하는 가장 중요한 단계인 ‘데이터 전처리(Data Preprocessing)’를 다룹니다.

이 시간의 핵심은 “기계(알고리즘)가 세상을 바라보는 방식”을 이해하는 것입니다. 사람은 나이 60세와 연봉 1억 원을 직관적으로 구분하지만, 기계는
단순히 숫자의 크기(Magnitude)로만 판단합니다. 또한, 기계는 텍스트를 읽을 수 없으므로 모든 정보를 숫자로 변환해주는 통역 과정이 필요합니다.


# 📘 [1일차 4교시] 4.1. 데이터 전처리: 기계와 소통하기 위한 번역과 조율

## 1. 머신러닝의 첫 번째 장벽: 기계는 숫자밖에 모른다

우리가 다루는 현실 세계의 데이터는 매우 다양하다. 엑셀 파일 안에는 숫자로 된 '나이'와 '키'도 있지만, 문자로 된 '성별(남/여)', '혈액형(A/B/O/AB)', '거주지(서울/부산)'도 섞여 있다. 사람은 이 표를 보고 직관적으로 이해하지만, 컴퓨터(머신러닝 알고리즘)는 텍스트를 읽을 수 없다.

### 1) 기계의 언어는 오직 수학이다
머신러닝의 모든 과정은 더하기, 빼기, 곱하기, 나누기의 연속이다.
우리가 배운 회귀식 $y = w x + b$를 떠올려보자.
*   나이($x$)가 20살이다: $w \times 20$ (계산 가능)
*   성별($x$)이 남자다: $w \times \text{'남자'}$ (계산 불가능)

컴퓨터에게 '남자'라는 글자를 곱하라고 하면 에러를 뱉어내고 멈춰버린다. 따라서 우리는 세상의 모든 정보를 숫자로 바꿔줘야 한다. 이것이 데이터 전처리의 첫 번째 이유이다.

### 2) 숫자의 크기가 곧 중요도는 아니다
더 큰 문제는 숫자로 되어 있어도 발생한다.
*   환자 A: 나이 50세, 백혈구 수치 5,000
*   환자 B: 나이 55세, 백혈구 수치 5,500

사람은 "나이는 5살 차이 나고, 백혈구는 500 차이 난다"고 생각하며 각각의 단위(Unit)를 감안해서 본다. 하지만 기계는 단위라는 개념이 없다. 기계의 눈에는 단순히 5와 500의 차이만 보인다.
기계는 이렇게 생각한다.
> "나이는 고작 5 변했는데, 백혈구는 무려 500이나 변했네? 백혈구 수치가 나이보다 100배 더 중요한 정보구나!"

이것은 명백한 오해다. 나이 5살의 차이는 생물학적으로 매우 클 수 있지만, 백혈구 수치 500의 차이는 정상 범위 내의 사소한 변동일 수 있다. 기계가 숫자의 절대적인 크기(Magnitude)에 압도당해서 잘못된 판단을 하지 않도록, 숫자들의 체급을 맞춰주는 작업이 필요하다.

---

## 2. 스케일링(Scaling): 코끼리와 개미를 한 저울에 올리는 법

서로 다른 단위를 가진 변수들을 비교 가능한 형태로 맞춰주는 작업을 '스케일링(Scaling)'이라고 한다. 헬스케어 데이터는 특히 단위가 제각각이기 때문에(mg, cm, kg, count/mL 등) 스케일링이 필수적이다.

대표적인 두 가지 방법인 표준화와 정규화를 비교해 본다.

### 1) 표준화 (Standardization): 등수를 매겨보자 (Z-score)
표준화는 데이터가 평균으로부터 얼마나 떨어져 있는지를 나타내는 척도이다.
*   원리: 모든 데이터의 평균을 0, 분산(퍼짐 정도)을 1로 강제 조정한다.
*   수식: $z = \frac{x - \text{평균}}{\text{표준편차}}$
*   해석:
    *   값이 0이다 $\rightarrow$ "딱 평균이다."
    *   값이 +1이다 $\rightarrow$ "평균보다 조금 높다 (상위권)."
    *   값이 -2이다 $\rightarrow$ "평균보다 매우 낮다 (하위권)."

#### 헬스케어 예시: 키와 몸무게의 비교
*   철수: 키 190cm (평균 175, 표준편차 5), 몸무게 100kg (평균 70, 표준편차 10)
*   기계의 착각: "190 > 100 이니까 키가 더 큰 숫자네."
*   표준화 적용:
    *   키 Z-점수: $(190 - 175) / 5 = +3.0$
    *   몸무게 Z-점수: $(100 - 70) / 10 = +3.0$
*   결론: 표준화 후 기계는 "철수의 키와 몸무게는 둘 다 평균보다 3표준편차만큼 높은, 동등하게 엄청난 수준이구나"라고 올바르게 이해한다. 두 변수의 영향력을 공평하게 만든 것이다.

### 2) 정규화 (Normalization): 0과 1 사이로 압축하기 (Min-Max Scaling)
정규화는 모든 데이터를 무조건 최솟값 0, 최댓값 1 사이의 비율로 변환한다.
*   원리: 가장 작은 값을 0, 가장 큰 값을 1로 잡고 나머지는 그 사이의 비율로 표시한다.
*   수식: $x_{new} = \frac{x - \text{최소}}{\text{최대} - \text{최소}}$
*   해석: "전체 범위에서 몇 퍼센트(%) 위치에 있는가?"

#### 헬스케어 예시: 통증 척도와 삶의 질 점수
*   통증 척도(VAS): 0점(통증 없음) ~ 10점(극심한 통증)
*   삶의 질 설문: 0점(최악) ~ 100점(최고)
*   환자 A가 통증 5점, 삶의 질 50점이라고 하자.
    *   그냥 넣으면 기계는 5와 50으로 인식하여 삶의 질을 10배 중요하게 본다.
    *   Min-Max 스케일링을 하면 둘 다 0.5 (딱 중간)가 된다.
    *   이제 기계는 두 지표를 동일한 가중치로 다룰 수 있다.

### 3) 언제 무엇을 써야 할까?
*   표준화(Standardization): 데이터에 이상치(Outlier)가 있거나, 분포가 정규분포에 가까울 때 유리하다. 대부분의 머신러닝 모델(선형 회귀, 로지스틱 회귀, SVM 등)에서 기본적으로 사용한다.
*   정규화(Normalization): 데이터의 범위가 정해져 있을 때(이미지 픽셀 0~255 등)나, 데이터가 정규분포가 아닐 때 유용하다.

---

## 3. 인코딩(Encoding): 문자를 숫자로 번역하는 기술

컴퓨터에게 '남자', 'B형', '서울' 같은 범주형(Categorical) 데이터를 숫자로 바꿔주는 과정을 '인코딩'이라고 한다. 여기서 초심자가 가장 많이 범하는 실수가 있다.

### 1) 레이블 인코딩 (Label Encoding): 위험한 번호 매기기
가장 단순한 방법은 각 글자에 번호를 붙이는 것이다.
*   데이터: 혈액형 [A형, B형, O형, AB형]
*   변환: A=1, B=2, O=3, AB=4

이렇게 변환해서 모델에 넣으면 무슨 일이 벌어질까? 기계는 이 숫자를 수학적인 크기로 받아들인다.
> "어? B형(2)은 A형(1)보다 2배 더 크네?"
> "A형(1)이랑 B형(2)을 더하면 O형(3)이 되는구나?"

혈액형에는 크기나 순서가 없다. B형이 A형보다 우월하거나 큰 존재가 아니다. 하지만 레이블 인코딩을 하면 기계는 "혈액형 숫자가 클수록 결과값($y$)에 더 큰 영향을 준다"는 엉터리 규칙을 학습하게 된다. 이를 '순서의 오류'라고 한다.

#### 언제 써야 하는가? (순서가 있을 때)
물론 레이블 인코딩이 유용한 경우도 있다. 데이터 자체에 '순서(Rank)'가 있는 경우다.
*   암의 기수: 1기 < 2기 < 3기 < 4기
*   통증 정도: 경미함(Mild) < 중등도(Moderate) < 심각함(Severe)
이때는 1, 2, 3, 4로 바꿔도 된다. 숫자의 크기가 실제 심각도의 크기를 반영하기 때문이다.

### 2) 원-핫 인코딩 (One-Hot Encoding): 모두를 평등하게
순서가 없는 대부분의 범주형 데이터(명목형 변수)를 처리하기 위해, 우리는 '원-핫 인코딩'을 사용한다.
이는 하나의 변수를 여러 개의 스위치(0 또는 1)로 쪼개는 방식이다.

*   데이터: 혈액형 [A, B, O, AB]
*   변환:
    *   A형입니까? [1, 0, 0, 0]
    *   B형입니까? [0, 1, 0, 0]
    *   O형입니까? [0, 0, 1, 0]
    *   AB형입니까? [0, 0, 0, 1]

이제 A형, B형, O형은 서로 독립적인 존재가 되었다. 크기 비교도 불가능하고 더하기 빼기도 안 된다. 오직 "이 속성을 가졌는가(1), 안 가졌는가(0)"만 판단한다.
이렇게 하면 기계가 "B형이 A형보다 크다"는 오해를 하지 않고, 각 혈액형 별로 공정한 가중치($w$)를 계산할 수 있다.

---

## 4. 데이터 누수(Data Leakage): 모의고사 답지를 미리 보지 마라

전처리를 할 때 가장 중요하면서도 많이 실수하는 개념이 바로 '데이터 누수'이다.

### 1) 상황 설정
우리는 모델을 학습시키기 위해 데이터를 훈련용(Train)과 테스트용(Test)으로 나눈다.
*   훈련용: 공부할 때 쓰는 교과서.
*   테스트용: 나중에 실력을 검증할 수능 시험지.

### 2) 잘못된 전처리 (흔한 실수)
1.  전체 데이터(훈련+테스트)를 몽땅 가져온다.
2.  전체 데이터의 평균과 분산을 구해서 한꺼번에 스케일링(표준화)을 한다.
3.  그다음에 훈련용과 테스트용으로 나눈다.

이것은 명백한 반칙이다. 왜냐하면 스케일링을 하는 과정에서 '테스트 데이터의 정보(평균값)'가 모델에 미리 흘러 들어갔기 때문이다. 수능 시험 문제의 평균 점수를 미리 알고 공부하는 것과 같다. 이렇게 만들면 테스트 점수는 잘 나오겠지만, 막상 현실에 투입하면 성능이 엉망이 된다.

### 3) 올바른 전처리 (정석)
1.  데이터를 먼저 훈련용과 테스트용으로 쪼갠다 (Split).
2.  훈련 데이터만 가지고 평균과 분산을 계산한다. (기준 수립)
3.  그 기준(훈련 데이터의 평균)을 가지고 훈련 데이터를 변환한다.
4.  테스트 데이터도 '훈련 데이터의 기준'으로 변환한다.
    *   *주의:* 테스트 데이터의 평균을 새로 구하면 안 된다! 기계가 알고 있는 기준은 오직 훈련 데이터뿐이어야 한다.

---

## 5. 요약:

1.  기계와의 소통: 머신러닝은 수학 연산이므로, 문자는 인코딩을 통해 숫자로, 크기가 제각각인 숫자는 스케일링을 통해 비슷한 체급으로 맞춰줘야 한다.
2.  스케일링:
    *   표준화(Standardization): 평균 0, 분산 1. (이상치에 강함, 일반적)
    *   정규화(Normalization): 0 ~ 1 사이 압축. (절대적 범위가 있을 때)
3.  인코딩:
    *   레이블 인코딩: 순서가 있는 데이터(암 1기~4기)에만 써라.
    *   원-핫 인코딩: 순서가 없는 데이터(성별, 지역)는 스위치(0/1)로 쪼개라.
4.  원칙: 전처리의 기준(평균, 최댓값 등)은 반드시 훈련 데이터(Train Set)에서만 가져와야 한다. 테스트 데이터를 미리 엿보지 마라(Data Leakage 방지).

이 개념들을 머릿속에 잘 넣어두고, 이제 노트북 실습을 통해 실제로 데이터를 주무르는 법을 익혀보자.

# 📘 \[4교시\] 데이터 전처리: 기계를 위한 번역과 조율 (Scaling & Encoding) 정리

## 4.1. \[개념 심화\] 기계가 오해하지 않도록 데이터를 다듬는 기술

### 1) 스케일링(Scaling): “코끼리의 무게와 벼룩의 점프 높이 비교하기”

머신러닝 모델(특히 선형 회귀)은 ‘숫자가 클수록 중요하다’라고
착각하는 경향이 있습니다.

- 문제 상황: 환자 데이터에 두 가지 변수가 있습니다.
  - 변수 A: 나이 (범위: 0 ~ 100)
  - 변수 B: 백혈구 수치 (범위: 4,000 ~ 10,000)
- 기계의 착각: “백혈구 수치는 10,000이나 되고 나이는 100밖에 안
  되네? 백혈구 수치가 나이보다 100배 더 중요한 정보구나!”
  - 실제로는 나이 1살의 차이가 백혈구 1개의 차이보다 훨씬 치명적일 수
    있습니다. 하지만 기계는 단위(Unit)를 모르기 때문에 숫자의 절대적
    크기에 압도당합니다.
- 해결책: 모든 변수의 범위를 비슷하게 맞춰주어야 합니다. 이를
  스케일링이라고 합니다.
  - 표준화 (Standardization): 평균을 0, 분산을 1로 맞춤.
    (정규분포화)
  - 정규화 (Normalization): 최솟값을 0, 최댓값을 1로 맞춤. (압축)

### 2) 인코딩(Encoding): “기계에게 한국어 가르치기”

머신러닝 알고리즘은 수학 공식을 기반으로 합니다. 즉, 덧셈, 뺄셈,
곱셈이 불가능한 데이터는 입력받을 수 없습니다.

- 문제 상황: ‘혈액형’ 데이터가 \[A형, B형, O형, AB형\]으로 되어
  있습니다.
  - 수식: $y = w \times \text{혈액형} + b$
  - $A형 \times 2$는 무엇인가? 계산할 수 없습니다.
- 해결책 1 (Label Encoding): 각 글자에 번호를 매깁니다. (A=1, B=2,
  O=3, AB=4)
  - *치명적 문제:* 기계는 이를 수학적으로 해석합니다. “4(AB형)는
    2(B형)보다 2배 더 크구나!”, “1(A형) + 2(B형) = 3(O형)이구나!”
  - 순서(Rank)가 없는 데이터에 번호를 매기면 기계가 엉뚱한 규칙을
    배웁니다.
- 해결책 2 (One-Hot Encoding): 각 항목을 별도의 스위치(0/1)로
  만듭니다.
  - A형: \[1, 0, 0, 0\]
  - B형: \[0, 1, 0, 0\]
  - 이제 기계는 “A형이다/아니다”로만 판단하므로, 크기 비교의 오류에
    빠지지 않습니다.


## 4.2. \[예제 1\] 표준화 (StandardScaler): 평균을 0으로 맞추기

가장 많이 사용되는 스케일링 기법입니다. 데이터의 단위가 다를 때 분포를
통일시킵니다.

상황: 단위가 전혀 다른 ‘나이’와 ’연봉’ 데이터를 기계가 공평하게 보게
만듭니다.

``` python
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# 1. 데이터 준비
# 나이(Age): 20~60세 (작은 숫자)
# 연봉(Salary): 3000~9000만원 (큰 숫자)
data = np.array([
    [20, 3000],
    [30, 4500],
    [40, 6000],
    [50, 7500],
    [60, 9000]
])
df = pd.DataFrame(data, columns=['Age', 'Salary'])

print("=== 원본 데이터 (평균과 표준편차) ===")
print(df.mean())
print("-" * 30)

# 2. 스케일링 적용 (StandardScaler)
scaler = StandardScaler()
# fit: 데이터의 평균과 표준편차를 계산해라
# transform: 계산된 값으로 데이터를 바꿔라
scaled_data = scaler.fit_transform(df)

df_scaled = pd.DataFrame(scaled_data, columns=['Age', 'Salary'])

print("=== 스케일링 후 데이터 (평균은 0, 분산은 1에 가까워짐) ===")
print(df_scaled.mean().round(2)) # 거의 0
print(df_scaled.std().round(2))  # 거의 1
display(df_scaled)

# 설명:
# 나이 20세는 -1.41, 60세는 +1.41로 변했습니다.
# 연봉 3000은 -1.41, 9000은 +1.41로 변했습니다.
# 이제 기계는 두 변수를 '동등한 영향력'을 가진 데이터로 인식합니다.
```
> 📖 문제 풀이 가이드
>
> 데이터의 단위(Unit)를 통일하는 표준화(Standardization) 실습입니다.
> - 문제점: 나이(20~60)와 연봉(3000~9000)은 숫자의 크기가 너무 다릅니다. 기계는 연봉이 훨씬 중요하다고 착각할 수 있습니다.
> - 해결책: `StandardScaler`를 사용하여 평균이 0, 분산이 1이 되도록 맞춥니다.
> - 변환 함수: $z =
rac{x - 	ext{mean}}{	ext{std}}$
> - 결과: 모든 데이터가 0을 중심으로 모이게 되어, 변수 간 크기 차이가 사라집니다.


In [4]:
# do write code
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
data = np.array([[20,3000], [30,4500],[40,6000],[50,7500],[60,9000]])

df = pd.DataFrame(data, columns=['Age', 'Salary'])

print("=== 원본 데이터 (평균과 표준편차) ===")
print(df.mean())
print("-"*30)

scaler = StandardScaler()

scaled_data = scaler.fit_transform(df)

df_scaled = pd.DataFrame(scaled_data, columns=['Age', 'Salary'])

print("=== 스케일링 후 데이터 (평균은 0, 분산은 1에 가까워짐) ===")
print(df_scaled.mean().round(2))
print(df_scaled.std().round(2))
display(df_scaled)

=== 원본 데이터 (평균과 표준편차) ===
Age         40.0
Salary    6000.0
dtype: float64
------------------------------
=== 스케일링 후 데이터 (평균은 0, 분산은 1에 가까워짐) ===
Age       0.0
Salary   -0.0
dtype: float64
Age       1.12
Salary    1.12
dtype: float64


Age    Salary
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

## 4.3. \[예제 2\] 정규화 (MinMaxScaler): 0과 1 사이로 압축하기

데이터를 무조건 0(최소)과 1(최대) 사이의 값으로 변환합니다. 이미지
데이터나, 최댓값/최솟값이 정해져 있는 경우 유용합니다.

상황: 환자의 통증 지수(0~10)와 행복 지수(0~100)를 동일한 0~1 척도로
비교합니다.

``` python
from sklearn.preprocessing import MinMaxScaler

# 1. 데이터 준비
# 통증: 0~10
# 행복: 0~100
data_m = np.array([
    [0, 10],   # 통증 최소, 행복 최소
    [5, 50],   # 중간
    [10, 80]   # 통증 최대, 행복 높음
])

# 2. 스케일링 적용 (MinMaxScaler)
min_max_scaler = MinMaxScaler()
scaled_m = min_max_scaler.fit_transform(data_m)

print("=== 원본 데이터 ===")
print(data_m)
print("\n=== Min-Max 스케일링 후 (0~1 범위) ===")
print(scaled_m)

# 설명:
# 통증 5는 0.5가 되고, 행복 50도 약 0.57이 되었습니다.
# 서로 다른 척도가 0~1 사이의 비율로 통일되었습니다.
```


> 📖 문제 풀이 가이드
>
> 데이터를 0과 1 사이로 압축하는 정규화(Normalization, Min-Max Scaling) 실습입니다.
> - 용도: 이미지 처리(픽셀 0~255)나, 최댓값/최솟값이 명확한 경우 주로 사용합니다.
> - 해결책: `MinMaxScaler`를 사용합니다.
> - 변환 함수: $x_{scaled} =
rac{x - x_{min}}{x_{max} - x_{min}}$
> - 주의: 이상치(Outlier)가 있으면 0~1 사이로 예쁘게 펴지지 않고 한쪽으로 찌그러질 수 있습니다.



In [6]:
# do write code
from sklearn.preprocessing import MinMaxScaler

data_m = np.array([
    [0,10],[5,50],[10,80]
])

min_max_scaler = MinMaxScaler()
scaled_m = min_max_scaler.fit_transform(data_m)

print("=== 원본 데이터 ===")
print(data_m)
print("\n=== Min-Max 스케일링 후 (0~1 범위) ===")
print(scaled_m)

=== 원본 데이터 ===
[[ 0 10]
 [ 5 50]
 [10 80]]

=== Min-Max 스케일링 후 (0~1 범위) ===
[[0.         0.        ]
 [0.5        0.57142857]
 [1.         1.        ]]


## 4.4. \[예제 3\] 레이블 인코딩 (Label Encoding): 순서가 중요할 때

범주형 데이터 중 ‘순서(Order)’나 ‘등급(Rank)’이 있는 경우에
사용합니다.

상황: 암의 기수(Stage)는 I기, II기, III기 순서로 심각도가
높아집니다. 이때는 숫자의 크기가 의미를 가집니다.

``` python
from sklearn.preprocessing import LabelEncoder

# 1. 데이터 준비 (순서가 있는 범주형)
cancer_stages = ['Stage I', 'Stage II', 'Stage I', 'Stage III', 'Stage II']

# 2. 인코딩 적용
le = LabelEncoder()
encoded_stages = le.fit_transform(cancer_stages)

print("원본 데이터:", cancer_stages)
print("변환 데이터:", encoded_stages)

# 클래스 확인 (0, 1, 2가 각각 무엇인지)
print("클래스 순서:", le.classes_)

# 설명:
# Stage I -> 0
# Stage II -> 1
# Stage III -> 2
# 여기서는 2(Stage III)가 0(Stage I)보다 크다는 것이 의학적으로 말이 됩니다.
# 따라서 이 경우에는 Label Encoding을 써도 안전합니다.
```


> 📖 문제 풀이 가이드
>
> 순서가 있는(Ordinal) 범주형 데이터를 숫자로 바꾸는 레이블 인코딩(Label Encoding)입니다.
> - 상황: 암의 기수(Stage I, II, III)처럼 1기보단 2기가, 2기보단 3기가 더 심각한 경우입니다.
> - 방법: `LabelEncoder`를 사용하면 글자를 가나다/알파벳 순서대로 0, 1, 2...로 매핑해줍니다.
> - 주의: 만약 순서가 중요한 데이터가 아니라면(예: 사과, 배, 딸기), 이 방식을 쓰면 안 됩니다. (배가 사과보다 2배 '크다'고 오해함)



In [7]:
# do write code
from sklearn.preprocessing import LabelEncoder

cancer_stages = ['Stage I', 'Stage II', 'Stage I', 'Stage III', 'Stage II']

le = LabelEncoder()
encoded_stage = le.fit_transform(cancer_stages)

print("원본 데이터:", cancer_stages)
print("변환 데이터:", encoded_stage)

print("클래스 순서:", le.classes_)

원본 데이터: ['Stage I', 'Stage II', 'Stage I', 'Stage III', 'Stage II']
변환 데이터: [0 1 0 2 1]
클래스 순서: ['Stage I' 'Stage II' 'Stage III']


## 4.5. \[예제 4\] 원-핫 인코딩 (One-Hot Encoding): 순서가 없을 때

범주형 데이터 간에 우열이나 순서가 없을 때 사용합니다. 대부분의 범주형
데이터(성별, 지역, 혈액형 등)가 여기에 해당합니다.

상황: 환자의 거주 지역(서울, 부산, 제주)은 순서가 없습니다. 서울이
제주보다 2배 큰 값이 아닙니다.

``` python
from sklearn.preprocessing import OneHotEncoder

# 1. 데이터 준비 (2차원 배열 형태여야 함)
regions = np.array([['Seoul'], ['Busan'], ['Jeju'], ['Seoul']])

# 2. 인코딩 적용
# sparse=False: 결과를 보기 편한 일반 배열(numpy array)로 반환하라는 옵션
ohe = OneHotEncoder(sparse_output=False)
encoded_regions = ohe.fit_transform(regions)

print("=== One-Hot Encoding 결과 ===")
print(encoded_regions)

# 컬럼 이름 확인
print("생성된 컬럼:", ohe.get_feature_names_out(['City']))

# 설명:
# Seoul -> [0, 0, 1]
# Busan -> [1, 0, 0]
# 각 도시가 독립적인 컬럼(변수)으로 분리되었습니다.
# 이제 기계는 도시 간에 크기 비교를 하지 않고, '서울이냐 아니냐'로만 판단합니다.
```


> 📖 문제 풀이 가이드
>
> 순서가 없는(Nominal) 범주형 데이터를 처리하는 원-핫 인코딩(One-Hot Encoding)입니다.
> - 상황: 서울, 부산, 제주처럼 지역 간에 우열이 없는 경우입니다.
> - 방법: `OneHotEncoder`를 사용합니다. 해당되는 항목만 1, 나머지는 0인 긴 배열을 만듭니다.
> - 결과: `[1, 0, 0]`, `[0, 1, 0]` 처럼 서로 독립적인 스위치가 되어, 기계가 크기를 비교하지 않고 '종류'로만 인식하게 됩니다.



In [8]:
# do write code
from sklearn.preprocessing import OneHotEncoder

regions = np.array([['Seoul'],['Busan'],['Jeju'],['Seoul']])

ohe = OneHotEncoder(sparse_output=False)
encoded_regions = ohe.fit_transform(regions)

print("=== One-Hot Encoding 결과 ===")
print(encoded_regions)

print("생성된 컬럼:", ohe.get_feature_names_out(['City']))

=== One-Hot Encoding 결과 ===
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
생성된 컬럼: ['City_Busan' 'City_Jeju' 'City_Seoul']


## 4.6. \[예제 5\] \[중요\] 실전 파이프라인: 나누고(Split), 적용하라!

전처리를 할 때 초보자가 가장 많이 하는 실수는 ‘전체 데이터를 먼저
스케일링하고 나서 학습/테스트로 나누는 것’입니다. 이는 데이터
누수(Data Leakage)라는 치명적인 오류입니다.

원칙: 모의고사(Test Set)의 정보(평균, 분산)를 미리 훔쳐보고
공부(Train)하면 반칙입니다. 학습 데이터만 가지고 기준을 세워야 합니다.

상황: 의료비 데이터를 올바른 순서로 전처리하기.

``` python
from sklearn.model_selection import train_test_split

# 1. 전체 데이터 준비 (나이, 의료비)
X = np.array([[20], [30], [40], [50], [60], [70]]) # 나이
y = np.array([100, 150, 200, 250, 300, 350])       # 의료비

# 2. [Step 1] 무조건 쪼개기부터! (Train / Test Split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print("학습 데이터:", X_train.flatten())
print("테스트 데이터:", X_test.flatten())

# 3. [Step 2] 학습 데이터로만 기준 잡기 (fit)
scaler = StandardScaler()
scaler.fit(X_train) # Train 데이터의 평균과 표준편차를 계산함

# 4. [Step 3] 변환하기 (transform)
# Train 데이터 변환
X_train_scaled = scaler.transform(X_train)

# Test 데이터 변환 (중요: scaler.fit(X_test)를 하면 안 됨! 위에서 잡은 기준으로 변환만 함)
X_test_scaled = scaler.transform(X_test)

print("\n=== 올바르게 스케일링된 데이터 ===")
print("Train Scaled:", X_train_scaled.flatten().round(2))
print("Test Scaled: ", X_test_scaled.flatten().round(2))

# 설명:
# 테스트 데이터(모의고사)는 학습 과정에 전혀 관여하지 않았습니다.
# 이것이 올바른 전처리 프로세스입니다.
```


> 📖 문제 풀이 가이드
>
> 데이터 누수(Data Leakage)를 방지하는 올바른 전처리 순서를 익힙니다.
> - 핵심 원칙: "모의고사(Test Set)는 절대 보지 마라!"
> - 실수: 전체 데이터를 `fit`하고 나서 나누면, 테스트 데이터의 평균과 분산 정보가 훈련 과정에 새어 들어갑니다.
> - 정석:
>   1. 데이터를 먼저 나눈다 (`train_test_split`).
>   2. 오직 학습 데이터(Train Set)로만 기준을 잡는다 (`scaler.fit(X_train)`).
>   3. 그 기준으로 학습 데이터와 테스트 데이터를 변환한다 (`scaler.transform`).



In [9]:
# do write code
from sklearn.model_selection import train_test_split

x = np.array([[20],[30],[40],[50],[60],[70]])
y = np.array([100,150,200,250,300,350])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

print("학습 데이터:", x_train.flatten())
print("테스트 데이터:", x_test.flatten())

scaler = StandardScaler()
scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)

x_test_scaled = scaler.transform(x_test)

print("\n=== 올바르게 스케일링된 데이터 ===")
print("Train Scaled:", x_train_scaled.flatten().round(2))
print("Test Scaled: ", x_test_scaled.flatten().round(2))


학습 데이터: [70 40 60 50]
테스트 데이터: [20 30]

=== 올바르게 스케일링된 데이터 ===
Train Scaled: [ 1.34 -1.34  0.45 -0.45]
Test Scaled:  [-3.13 -2.24]
